version: '2'
services:
  test_db:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
