version: '2'
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    expose:
      - "6379"
