"""initial migration

Revision ID: 67f49cdd66f3
Revises: 
Create Date: 2022-04-03 23:07:43.235403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f49cdd66f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ticker',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'ticker_price',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('ticker_id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('price', sa.DECIMAL(), nullable=True),
        sa.ForeignKeyConstraint(
            ['ticker_id'],
            ['ticker.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_ticker_price_created_at'), 'ticker_price', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticker_price_ticker_id'), 'ticker_price', ['ticker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_price_ticker_id'), table_name='ticker_price')
    op.drop_index(op.f('ix_ticker_price_created_at'), table_name='ticker_price')
    op.drop_table('ticker_price')
    op.drop_table('ticker')
    # ### end Alembic commands ###
